
title : 一些知识
description: 个人掌握的零碎知识

Author:
  Name: 一个路过的假人
  Info: 一个掌握了各种技能的嵌入式软件工程师
  Intro: 总感觉你们在背着我学习
  EXP : 10
  State: 存在

collections:
  classes:
    output: true

default: 
  - scope:
      path: ""
      type: "classes"
    values:
      layout: "class"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge


